on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -la
  job2:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
