name: 打包项目
on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: build操作
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 安装依赖
        run: npm install

      - name: 打包项目
        run: npm run build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: master
          folder: build
