name: 打包项目
on: push

# github
# permissions:
#   contents: write

jobs:
  npm-build:
    name: build操作
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      # github CI/CD
      # - name: 安装依赖
      #   run: npm install

      # - name: 打包项目
      #   run: npm run build

      # - name: 部署
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages
      #     folder: dist

      # docker
      - name: 登录dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建镜像
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ebond/react-actions:latest
